version: 1.0.{build}-{branch}

skip_tags: true

environment:
  matrix:
    - RUBY_VERSION: 27-x64
    - RUBY_VERSION: 27

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundler env
  - gem install bundler
  - bundle install

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rspec

build: off
