version: 1.0.{build}

skip_tags: true

environment:
  matrix:
    - RUBY_VERSION: "27-x64"
    - RUBY_VERSION: "27"

install:
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler
  - bundler env
  - bundle install

test_script:
  - bundle exec rspec

build: off
